name: 'Unity Build'
description: 'A Github Action to build Unity projects using command line arguments.'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  project-path:
    description: 'Path to the Unity project.'
    required: true
    default: ''
  build-target:
    description: 'Unity build target. One of "linux", "macos", "windows"'
    required: true
    default: ''
  build-method:
    description: 'Editor method to execute.'
    required: true
    default: ''
outputs:
  success:
    description: "Success"
    value: ${{ steps.unity-editor-run.outcome == 'success' }}
runs:
  using: 'composite'
  steps:
    - name: 'Setup Env'
      run: |
        export UNITY_NO_BANNER=1 && echo "UNITY_NO_BANNER=1" >>$GITHUB_ENV
        export UNITY_NON_INTERACTIVE=1 && echo "UNITY_NON_INTERACTIVE=1" >>$GITHUB_ENV
        export UNITY_NO_PAGER=1 && echo "UNITY_NO_PAGER=1" >>$GITHUB_ENV
        export UNITY_NO_ELEVATE=1 && echo "UNITY_NO_ELEVATE=1" >>$GITHUB_ENV
        export UNITY_NO_UPDATE_CHECK=1 && echo "UNITY_NO_UPDATE_CHECK=1" >>$GITHUB_ENV
        export UNITY_NO_CRASH_REPORT=1 && echo "UNITY_NO_CRASH_REPORT=1" >>$GITHUB_ENV
        export UNITY_NO_CONSENT_PROMPT=1 && echo "UNITY_NO_CONSENT_PROMPT=1" >>$GITHUB_ENV

        export UNITY_VERBOSE=1 && echo "UNITY_VERBOSE=1" >>$GITHUB_ENV

        export UNITY_CLI_CHANNEL=beta && echo "UNITY_CLI_CHANNEL=beta" >>$GITHUB_ENV
      shell: bash

    - name: 'Setup Unity'
      if: ${{ (runner.os == 'Linux') || (runner.os == 'macOS') }}
      run: |
        curl -fsSL https://public-cdn.cloud.unity3d.com/hub/prod/cli/install.sh | bash
        unity --version
      shell: bash
    - name: 'Setup Unity'
      if: ${{ (runner.os == 'Windows') }}
      run: |
        irm https://public-cdn.cloud.unity3d.com/hub/prod/cli/install.ps1 | iex
        unity --version
      shell: pwsh

    - name: 'Install Unity License'
      id: unity-license-install
      run: |
        mkdir -p "$HOME/.local/share/unity3d/Unity/"
        cat <<< "${{ env.UNITY_LICENSE }}" > "$HOME/.local/share/unity3d/Unity/Unity_lic.ulf"
      shell: bash

    - name: 'Install Unity Editor'
      id: unity-editor-install
      continue-on-error: true
      run: |
        UNITY_EDITOR_VERSION=$(grep 'm_EditorVersion:' "${{ inputs.project-path }}/ProjectSettings/ProjectVersion.txt" | sed 's/m_EditorVersion:[[:space:]]*//' | sed 's/[a-z].*//')
        echo "Detected Unity version: $UNITY_EDITOR_VERSION"
        if [ "${{ inputs.build-target }}" = "linux" ]; then
          UNITY_MODULES="linux-mono"
        elif [ "${{ inputs.build-target }}" = "macos" ]; then
          UNITY_MODULES="mac-mono"
        elif [ "${{ inputs.build-target }}" = "windows" ]; then
          UNITY_MODULES="windows-mono"
        else
          echo "Build target ${{ inputs.build-target }} is not valid!"
          exit 1
        fi
        unity install $UNITY_EDITOR_VERSION --module $UNITY_MODULES --childModules --accept-eula --yes
      shell: bash

    - name: 'Print Install Errors'
      if: ${{ steps.unity-editor-install.outcome == 'failure' }}
      run: |
        unity logs
        unity doctor
      shell: bash

    - name: 'Run Unity Editor'
      id: unity-editor-run
      continue-on-error: true
      if: ${{ steps.unity-editor-install.outcome == 'success' }}
      run: |
        unity run "${{ inputs.project-path }}" -- -username "${{ env.UNITY_EMAIL }}" -password "${{ env.UNITY_PASSWORD }}" -batchmode -nographics -quit -executeMethod "${{ inputs.build-method }}"
      shell: bash

    - name: 'Print Run Errors'
      if: ${{ steps.unity-editor-run.outcome == 'failure' }}
      run: |
        unity logs
        unity doctor
      shell: bash

    - name: 'Uninstall Unity License'
      if: ${{ steps.unity-license-install.outcome == 'success' }}
      run: |
        rm "$HOME/.local/share/unity3d/Unity/Unity_lic.ulf"
      shell: bash
