name: 'Unity Build'
description: 'A Github Action to build Unity projects using command line arguments.'
branding:
  icon: 'play-circle'
  color: 'blue'
inputs:
  project-path:
    description: 'Path to the Unity project.'
    required: true
    default: ''
  build-target:
    description: 'Unity build target. One of "linux", "macos", "windows"'
    required: true
    default: ''
  build-method:
    description: 'Editor method to execute.'
    required: true
    default: ''
outputs:
  outcome:
    description: "Outcome of the action"
    value: ${{ steps.final-outcome.outputs.outcome }}
runs:
  using: 'composite'
  steps:
    - name: 'Setup Env'
      run: |
        export UNITY_NO_BANNER=1 && echo "UNITY_NO_BANNER=1" >>$GITHUB_ENV
        export UNITY_NON_INTERACTIVE=1 && echo "UNITY_NON_INTERACTIVE=1" >>$GITHUB_ENV
        export UNITY_NO_PAGER=1 && echo "UNITY_NO_PAGER=1" >>$GITHUB_ENV
        export UNITY_NO_ELEVATE=1 && echo "UNITY_NO_ELEVATE=1" >>$GITHUB_ENV
        export UNITY_NO_UPDATE_CHECK=1 && echo "UNITY_NO_UPDATE_CHECK=1" >>$GITHUB_ENV
        export UNITY_NO_CRASH_REPORT=1 && echo "UNITY_NO_CRASH_REPORT=1" >>$GITHUB_ENV
        export UNITY_NO_CONSENT_PROMPT=1 && echo "UNITY_NO_CONSENT_PROMPT=1" >>$GITHUB_ENV

        export UNITY_VERBOSE=1 && echo "UNITY_VERBOSE=1" >>$GITHUB_ENV

        export UNITY_CLI_CHANNEL="beta" && echo "UNITY_CLI_CHANNEL=beta" >>$GITHUB_ENV
      shell: bash

    - name: 'Setup Unity'
      run: |
        sudo install -d /etc/apt/keyrings
        curl -fsSL https://hub.unity3d.com/linux/keys/public | sudo gpg --dearmor -o /etc/apt/keyrings/unityhub.gpg
        echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/unityhub.gpg] https://hub.unity3d.com/linux/repos/deb stable main" | sudo tee /etc/apt/sources.list.d/unityhub.list
        sudo apt update && sudo apt install unityhub
      shell: bash

    - name: 'Install Unity License'
      id: unity-license-install
      run: |
        mkdir -p "$HOME/.local/share/unity3d/Unity/"
        cat <<< "${{ env.UNITY_LICENSE }}" > "$HOME/.local/share/unity3d/Unity/Unity_lic.ulf"
      shell: bash

    - name: 'Install Unity Editor'
      id: unity-editor-install
      continue-on-error: true
      run: |
        UNITY_EDITOR_VERSION=$(grep 'm_EditorVersion:' "${{ inputs.project-path }}/ProjectSettings/ProjectVersion.txt" | sed 's/m_EditorVersion:[[:space:]]*//' | sed 's/[a-z].*//')
        echo "UNITY_EDITOR_VERSION=$UNITY_EDITOR_VERSION" >>$GITHUB_ENV
        echo "Detected Unity version: $UNITY_EDITOR_VERSION"
        unityhub --headless install --version $UNITY_EDITOR_VERSION

        unityhub --headless editors --installed

        if [ "${{ inputs.build-target }}" = "linux" ]; then
          echo "Installing Editor module linux-mono"
          unityhub --headless install-modules --version $UNITY_EDITOR_VERSION --module linux-mono --childModules
        elif [ "${{ inputs.build-target }}" = "macos" ]; then
          echo "Installing Editor module mac-mono"
          unityhub --headless install-modules --version $UNITY_EDITOR_VERSION --module mac-mono --childModules
        elif [ "${{ inputs.build-target }}" = "windows" ]; then
          echo "Installing Editor module windows-mono"
          unityhub --headless install-modules --version $UNITY_EDITOR_VERSION --module windows-mono --childModules
        fi
      shell: bash

    - name: 'Print Install Errors'
      if: ${{ steps.unity-editor-install.outcome == 'failure' }}
      run: |
        cat "$HOME/.config/UnityHub/logs"/*
      shell: bash

    - name: 'Run Unity Editor'
      id: unity-editor-run
      continue-on-error: true
      if: ${{ steps.unity-editor-install.outcome == 'success' }}
      run: |
        UNITY_EDITOR_BASE=$(unityhub --headless install-path --get)
        "$UNITY_EDITOR_BASE/$UNITY_EDITOR_VERSION/Editor/Unity"  -projectPath "${{ inputs.project-path }}" -username "${{ env.UNITY_EMAIL }}" -password "${{ env.UNITY_PASSWORD }}" -batchmode -nographics -quit -executeMethod "${{ inputs.build-method }}"
      shell: bash

    - name: 'Print Run Errors'
      if: ${{ steps.unity-editor-run.outcome == 'failure' }}
      run: |
        cat "$HOME/.config/UnityHub/logs"/*
      shell: bash

    - name: 'Uninstall Unity License'
      if: ${{ steps.unity-license-install.outcome == 'success' }}
      run: |
        rm "$HOME/.local/share/unity3d/Unity/Unity_lic.ulf"
      shell: bash

    - name: 'Set Outcome'
      id: final-outcome
      run: |
        if [ "${{ steps.unity-editor-run.outcome }}" = "success" ]; then
          exit 0
        else
          exit 1
        fi
      shell: bash
